import type { Metadata } from "next"; 
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer"; 
import { Toaster } from "react-hot-toast";
import { Inter, Manrope } from "next/font/google"; 
import ThemeProvider from "@/components/Providers/ThemeProviders";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "AutoMarket",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en" className={`${inter.variable} ${manrope.variable}`} suppressHydrationWarning>
      <body className="font-body bg-background">
        <ThemeProvider>

        <Navbar/>
        <div> 
            {children} 
        </div>
        <Toaster/>
        <Footer/>

        </ThemeProvider>
      </body>
    </html>
  );
}
